const data = {
    '1': {
        heading: 'February 5, 2022',
        body: `
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae elit eu enim fermentum lobortis nec auctor quam. Fusce non lorem quis lacus eleifend rutrum. Nulla eget mauris vel nisi sodales luctus. Integer volutpat convallis orci, vel fermentum risus vulputate non. Quisque nec tristique ipsum. Integer commodo diam vel lorem tincidunt, a rhoncus ante hendrerit. Nam condimentum orci non dolor dapibus blandit. Fusce ut sodales ante. Nulla facilisi. Phasellus interdum euismod justo, eget finibus turpis interdum nec.\n
        Donec placerat metus eget elit condimentum, eu vestibulum justo laoreet. Maecenas ultrices euismod velit, sit amet malesuada enim faucibus at. Nulla facilisi. Maecenas hendrerit risus et mi ultrices commodo. Sed malesuada nulla ut accumsan euismod. Cras tincidunt, metus non pharetra dignissim, nunc orci faucibus magna, ut ultricies magna velit sed est. Vestibulum id metus urna. Proin et quam a purus commodo mattis. Integer euismod erat at ipsum tincidunt, a lobortis nulla laoreet. Aliquam consequat ipsum sed sem volutpat, eget tempus libero finibus. Nullam lacinia dui sit amet tempor dictum. Ut vel augue eu eros dignissim pellentesque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Maecenas vel tellus in justo finibus feugiat.\n
        Curabitur sollicitudin vehicula nibh, vitae tincidunt nunc blandit non. Morbi vehicula, ante in suscipit efficitur, massa arcu aliquet magna, nec sodales purus enim eget purus. Integer tristique dui eu ante aliquam, eu aliquam neque efficitur. Nunc eu metus et leo dictum consectetur. Vivamus sed diam quis tellus efficitur molestie. Cras at tortor in justo tempus fringilla. Duis tincidunt massa quis tellus tempus, in tincidunt nulla sodales. In bibendum nunc a orci consequat, id tincidunt nisi dapibus. Vestibulum at consectetur lectus, sed fermentum enim. Vivamus ultricies elit et quam ultricies, ac ultricies mi consectetur. Nullam congue, sem a dapibus facilisis, nunc massa sodales dolor, ut lobortis quam nisi vitae dolor. Etiam vel est ut justo tincidunt facilisis. Nullam aliquam convallis sapien, nec bibendum odio aliquet nec. Quisque malesuada arcu id mi vestibulum, eu euismod arcu accumsan. Suspendisse potenti.\n
        Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut rutrum orci sit amet sapien eleifend, vitae molestie lorem laoreet. Aliquam lacinia eros nec nunc efficitur, a interdum quam commodo. Nulla facilisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Mauris ultricies auctor turpis, sit amet congue dui mattis non. Phasellus et nisi non orci aliquam fringilla. Nam faucibus lorem ac vestibulum fringilla. In sit amet odio nec nisi volutpat cursus. Ut non arcu in libero tempus gravida eget ut lectus. Integer varius neque ut nibh tincidunt, at euismod dui tempor. Sed dignissim consequat nulla, sit amet blandit mi finibus ac. Integer quis sagittis nisl. Sed pretium volutpat odio, nec condimentum arcu tincidunt et.\n
        Vestibulum nec bibendum felis. Nullam nec tortor lorem. Sed tincidunt, libero non posuere feugiat, ligula nisl fermentum sapien, vel aliquet risus sem vitae justo. Phasellus vel ante dolor. Suspendisse dapibus nulla eget justo varius, eget consequat ligula suscipit. Aliquam erat volutpat. Vivamus nec fermentum mauris. Sed et bibendum sapien, in fermentum libero. Nam ac elit id elit feugiat dictum. Etiam convallis turpis magna, in interdum quam vestibulum a. Integer id consequat magna. Sed dignissim bibendum tortor, a vestibulum tortor tincidunt et. Phasellus pulvinar nunc in nulla ultrices dignissim. Nullam a luctus mi. Sed ac faucibus eros. Sed vitae ante sit amet nulla rhoncus ultricies. Suspendisse non tempor libero.`,
    },
    '2': {
        heading: 'May 23, 2022',
        body: `
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae elit eu enim fermentum lobortis nec auctor quam. Fusce non lorem quis lacus eleifend rutrum. Nulla eget mauris vel nisi sodales luctus. Integer volutpat convallis orci, vel fermentum risus vulputate non. Quisque nec tristique ipsum. Integer commodo diam vel lorem tincidunt, a rhoncus ante hendrerit. Nam condimentum orci non dolor dapibus blandit. Fusce ut sodales ante. Nulla facilisi. Phasellus interdum euismod justo, eget finibus turpis interdum nec.\n
        Donec placerat metus eget elit condimentum, eu vestibulum justo laoreet. Maecenas ultrices euismod velit, sit amet malesuada enim faucibus at. Nulla facilisi. Maecenas hendrerit risus et mi ultrices commodo. Sed malesuada nulla ut accumsan euismod. Cras tincidunt, metus non pharetra dignissim, nunc orci faucibus magna, ut ultricies magna velit sed est. Vestibulum id metus urna. Proin et quam a purus commodo mattis. Integer euismod erat at ipsum tincidunt, a lobortis nulla laoreet. Aliquam consequat ipsum sed sem volutpat, eget tempus libero finibus. Nullam lacinia dui sit amet tempor dictum. Ut vel augue eu eros dignissim pellentesque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Maecenas vel tellus in justo finibus feugiat.\n
        Curabitur sollicitudin vehicula nibh, vitae tincidunt nunc blandit non. Morbi vehicula, ante in suscipit efficitur, massa arcu aliquet magna, nec sodales purus enim eget purus. Integer tristique dui eu ante aliquam, eu aliquam neque efficitur. Nunc eu metus et leo dictum consectetur. Vivamus sed diam quis tellus efficitur molestie. Cras at tortor in justo tempus fringilla. Duis tincidunt massa quis tellus tempus, in tincidunt nulla sodales. In bibendum nunc a orci consequat, id tincidunt nisi dapibus. Vestibulum at consectetur lectus, sed fermentum enim. Vivamus ultricies elit et quam ultricies, ac ultricies mi consectetur. Nullam congue, sem a dapibus facilisis, nunc massa sodales dolor, ut lobortis quam nisi vitae dolor. Etiam vel est ut justo tincidunt facilisis. Nullam aliquam convallis sapien, nec bibendum odio aliquet nec. Quisque malesuada arcu id mi vestibulum, eu euismod arcu accumsan. Suspendisse potenti.\n
        Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut rutrum orci sit amet sapien eleifend, vitae molestie lorem laoreet. Aliquam lacinia eros nec nunc efficitur, a interdum quam commodo. Nulla facilisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Mauris ultricies auctor turpis, sit amet congue dui mattis non. Phasellus et nisi non orci aliquam fringilla. Nam faucibus lorem ac vestibulum fringilla. In sit amet odio nec nisi volutpat cursus. Ut non arcu in libero tempus gravida eget ut lectus. Integer varius neque ut nibh tincidunt, at euismod dui tempor. Sed dignissim consequat nulla, sit amet blandit mi finibus ac. Integer quis sagittis nisl. Sed pretium volutpat odio, nec condimentum arcu tincidunt et.\n
        Vestibulum nec bibendum felis. Nullam nec tortor lorem. Sed tincidunt, libero non posuere feugiat, ligula nisl fermentum sapien, vel aliquet risus sem vitae justo. Phasellus vel ante dolor. Suspendisse dapibus nulla eget justo varius, eget consequat ligula suscipit. Aliquam erat volutpat. Vivamus nec fermentum mauris. Sed et bibendum sapien, in fermentum libero. Nam ac elit id elit feugiat dictum. Etiam convallis turpis magna, in interdum quam vestibulum a. Integer id consequat magna. Sed dignissim bibendum tortor, a vestibulum tortor tincidunt et. Phasellus pulvinar nunc in nulla ultrices dignissim. Nullam a luctus mi. Sed ac faucibus eros. Sed vitae ante sit amet nulla rhoncus ultricies. Suspendisse non tempor libero.`,
    },
    '3': {
        heading: 'November 18, 2023',
        body: `
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae elit eu enim fermentum lobortis nec auctor quam. Fusce non lorem quis lacus eleifend rutrum. Nulla eget mauris vel nisi sodales luctus. Integer volutpat convallis orci, vel fermentum risus vulputate non. Quisque nec tristique ipsum. Integer commodo diam vel lorem tincidunt, a rhoncus ante hendrerit. Nam condimentum orci non dolor dapibus blandit. Fusce ut sodales ante. Nulla facilisi. Phasellus interdum euismod justo, eget finibus turpis interdum nec.\n
        Donec placerat metus eget elit condimentum, eu vestibulum justo laoreet. Maecenas ultrices euismod velit, sit amet malesuada enim faucibus at. Nulla facilisi. Maecenas hendrerit risus et mi ultrices commodo. Sed malesuada nulla ut accumsan euismod. Cras tincidunt, metus non pharetra dignissim, nunc orci faucibus magna, ut ultricies magna velit sed est. Vestibulum id metus urna. Proin et quam a purus commodo mattis. Integer euismod erat at ipsum tincidunt, a lobortis nulla laoreet. Aliquam consequat ipsum sed sem volutpat, eget tempus libero finibus. Nullam lacinia dui sit amet tempor dictum. Ut vel augue eu eros dignissim pellentesque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Maecenas vel tellus in justo finibus feugiat.\n
        Curabitur sollicitudin vehicula nibh, vitae tincidunt nunc blandit non. Morbi vehicula, ante in suscipit efficitur, massa arcu aliquet magna, nec sodales purus enim eget purus. Integer tristique dui eu ante aliquam, eu aliquam neque efficitur. Nunc eu metus et leo dictum consectetur. Vivamus sed diam quis tellus efficitur molestie. Cras at tortor in justo tempus fringilla. Duis tincidunt massa quis tellus tempus, in tincidunt nulla sodales. In bibendum nunc a orci consequat, id tincidunt nisi dapibus. Vestibulum at consectetur lectus, sed fermentum enim. Vivamus ultricies elit et quam ultricies, ac ultricies mi consectetur. Nullam congue, sem a dapibus facilisis, nunc massa sodales dolor, ut lobortis quam nisi vitae dolor. Etiam vel est ut justo tincidunt facilisis. Nullam aliquam convallis sapien, nec bibendum odio aliquet nec. Quisque malesuada arcu id mi vestibulum, eu euismod arcu accumsan. Suspendisse potenti.\n
        Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut rutrum orci sit amet sapien eleifend, vitae molestie lorem laoreet. Aliquam lacinia eros nec nunc efficitur, a interdum quam commodo. Nulla facilisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Mauris ultricies auctor turpis, sit amet congue dui mattis non. Phasellus et nisi non orci aliquam fringilla. Nam faucibus lorem ac vestibulum fringilla. In sit amet odio nec nisi volutpat cursus. Ut non arcu in libero tempus gravida eget ut lectus. Integer varius neque ut nibh tincidunt, at euismod dui tempor. Sed dignissim consequat nulla, sit amet blandit mi finibus ac. Integer quis sagittis nisl. Sed pretium volutpat odio, nec condimentum arcu tincidunt et.\n
        Vestibulum nec bibendum felis. Nullam nec tortor lorem. Sed tincidunt, libero non posuere feugiat, ligula nisl fermentum sapien, vel aliquet risus sem vitae justo. Phasellus vel ante dolor. Suspendisse dapibus nulla eget justo varius, eget consequat ligula suscipit. Aliquam erat volutpat. Vivamus nec fermentum mauris. Sed et bibendum sapien, in fermentum libero. Nam ac elit id elit feugiat dictum. Etiam convallis turpis magna, in interdum quam vestibulum a. Integer id consequat magna. Sed dignissim bibendum tortor, a vestibulum tortor tincidunt et. Phasellus pulvinar nunc in nulla ultrices dignissim. Nullam a luctus mi. Sed ac faucibus eros. Sed vitae ante sit amet nulla rhoncus ultricies. Suspendisse non tempor libero.`,
    },
}
export default data